# -*- coding: utf-8 -*-
"""KelimeAnlamBulma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8f7OaeP1W1w8F8Kwcnl1qGQY_MAf95E
"""

import random
import os

kelimeler = {"which" : "Hangi",
"their" : "Onların",
"how" : "Nasıl",
"all" : "Tüm",
"any" : "Herhangi",
"over" : "Üzerinde",
"even" : "Hatta",
"sound" : "Ses",
"take" : "Almak",
"place" : "Yer",
"work" : "Çalışmak",
"life" : "Hayat",
"tell" : "Söylemek",
"good" : "İyi",
"give" : "Vermek",
"long" : "Uzun",
"make" : "Yapmak",
"thing" : "Şey",
"see" : "Görmek",
"look" : "Bakmak",
"call" : "Çağırmak",
"first" :"İlk",
"man" : "Adam",
"year" : "Yıl",
"find" : "Bulmak",
"time" : "Zaman",
"great" : "Harika",
"say" : "Söylemek",
"know ": "Bilmek",
"back" : "Geride",
"make" : "Yapmak",
"through" : "İçinden",
"keep" : "Saklamak",
"still" : "Hala",
"must" : "Gerekmek",
"live" : "Yaşamak",
"should" : "Gerek",
"place" : "Mekan",
"same" : "Aynı",
"tell" : "Anlatmak",
"another" : "Diğer",
"under" : "Altında",
"few" : "Az",
"own" : "Kendi"}

def oyun_baslat():
   print("Kelime Anlamı Tahmin Oyununa Hoşgeldiniz!")
   print("Her bir kelime için anlamını tahmin etmeye çalışın.")
   print("Çıkmak için 'çık' yazabilirsiniz.")


   puan = 0

   while True:
        # Rastgele bir kelime seç
        kelime, anlam = random.choice(list(kelimeler.items()))

        # Kelimeyi göster;
        print(f"\nKelime: {kelime}")
        tahmin = input("Bu kelime nedir? ")

        # Kullanıcının tahminini kontrol et
        if tahmin == anlam.lower():
            os.system("cls")
            print("Doğru tahmin! Tebrikler!")
            puan += 1
        elif tahmin == "çık":
            print("Oyundan çıkıyorsunuz...")
            break
        else:
            os.system("cls")
            print(f"Yanlış tahmin! Doğru cevap: {anlam}")
            puan -=1
            print(f"Puanınız:{puan}")

        print(f"Şu ana kadar {puan} puan kazandınız.")
        devam = input("Bir kelime daha tahmin etmek ister misiniz? (e/h): ").lower()
        if devam != 'e':
            print("Oyunu sonlandırdınız.")
            break

oyun_baslat()
